### PR TITLE
Prepare for 0.5.0 release

### PR DESCRIPTION
**Pull request by uazu**
- Split out QCellOwnerSeq from QCellOwner::fast_new
- Tidy up qcell.rs loose ends
- Polish up docs and examples
- CHANGELOG update
- Scripts for running clippy/doc/tests with all feature combinations
- Update compiletests

### CODE REVIEW

**Comment by uazu** [comment]
@geeklint @steffahn  If either of you want to review this patch (or the changes in general since 0.4.3) before I merge this and publish 0.5.0, please do so. I'll leave this up for a few days.

Sorry that this release has taken so long to get done. Covid and/or the vaccines have been messing with my brain and making me less able to get stuff done over the last few months, but I hope that's behind me now. I'll leave the planned TCell/TLCell no_std support for now, to not slow things down any further.

**Comment by geeklint** [comment]
A scan through and it all looks pretty good to me.  One thing, which is maybe more of a nitpick, is the explicit reference to addresses being 2^32 or 2^64;  Rust officially supports at least one platform with 16-bit addresses, and is forward compatible with platforms with greater than 64-bit addresses.

**Comment by uazu** [comment]
Thanks. I want to make it concrete, but I'll change the language to make it clearer and to not exclude other address-widths.

**Comment by uazu** [comment]
I've published crate version 0.5.0. I will now announce on users and perhaps reddit

**Pull request merged**
